### ISSUE TITLE
get DataND object as return value

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#14]
Hello,

it seems that there is no equivalent method, e.g. to get_along or interpolate, that return DataND object. 
I think this could be handy, e.g. to do a FFT on a reduced set of indices. At the moment one has to extract field and axes data, slice the data and axes and setup a new DataND object to do that.

Best regards, Sebastian

**Comment by helene-t** [comment]
Hello Sebastian,

Indeed, such methods had not been implemented yet. It is not such a simple issue in the case of periodicity. However, as a first step, the new DataND object could be rebuilt ignoring symmetries, simply using the axis values extracted during the `get_along` call. Of course one loses the compacity of linspace and periodic objects, but it should work as a first work around.

I created a new `get_data_along` method to do so, using the exact same syntax as `get_along` (see commit  [#3ec612a](https://github.com/Eomys/SciDataTool/commit/3ec612a2e36dbd1175a6def76ebcfd0a924a42a4)). It should also work with Fourier transforms. If you want to improve it to take periodicities and linspaces into account, feel free to modify this method (I do not have much time to work on this issue for the moment).

Let me know if this new method meets your needs.

Best regards, Helene

**Comment by SebGue** [comment]
Hello Helene,

thank you, thats okay for now. I wanted to use this method in pyleecans Solution class for the same purpose.

BTW: There is no class generator. Is it possible to use pyleecans gen. 'out of the box'?

BR Sebastian

**Comment by helene-t** [comment]
Yes, I use pyleecan's class generator (by copy/pasting the csv files into the ClassesRef folder). I then have to manually remove from the class files the lines concerning the logger, which is not available in SciDataTool, and I replace all occurences of "pyleecan" by "SciDataTool".
