### ISSUE TITLE
RMS mean and RMS sum

### ISSUE THREAD

**Issue by helene-t** [Eomys/SciDataTool#16]
Previously, the syntax `get_along("time=rms")` had been designed to return the RMS sum along the "time" axis. However, this syntax could be understood as an RMS mean. I therefore suggest to add both syntaxes to the parser: `get_along("time=sum_rms")` and `get_along("time=mean_rms")`.

Best regards,
Helene

**Comment by SebGue** [comment]
Hello Helene,

but RMS already has mean in it. What about a 'square_sum' without root instead? BR S

**Comment by helene-t** [comment]
You are right, let's call it "rss" for "root sum square" then?
