### ISSUE TITLE
[BC] Bug when rebuilding symmetries of signals with one sample

### ISSUE THREAD

**Issue by EmileDvs** [Eomys/SciDataTool#17]
Hello,

There is an issue in rebuild_symmetries when rebuilding a signal with one sample. In fact, rebuild_symmetries relies on the knowledge of at least two samples (more specifically on the gap between two samples) to correctly rebuild the full signal.

The best correction would be to add the gap between two samples in the dict of symmetries such as:
`symmetries={"antiperiod": 2, "delta": 0.05}`

Best regards,
Emile

**Comment by helene-t** [comment]
Solved in [this commit](https://github.com/Eomys/SciDataTool/commit/b79d38df812ba2f8361f6aa4173c1948885b8cee).
