### ISSUE TITLE
import error

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#2]
Hello Helene,

I got a further error that can be reproduced with the following code

```
from SciDataTool import Data1D, DataTime
from numpy import linspace

time = linspace(0, 1, 8, endpoint=False)    
field = linspace(0, 1, 8, endpoint=False)    

Time = Data1D(name="time", unit="s", values=time)
y = DataTime(name="TestData",axes=[Time],values=field)

y_ = y.time_to_freq().freq_to_time()

```
Error Message:
ImportError: Can't use DataFreq method freq_to_time: cannot import name 'DataTime' from partially initialized module 'SciDataTool' (most likely due to a circular import) (C:\Program Files\Python38\lib\site-packages\SciDataTool\__init__.py)

Edit: This issue also happens, if I setup a DataFreq object directly and try to use the freq_to_time method.

Best regards, Sebastian

**Comment by helene-t** [comment]
Hello Sebastian,

I just corrected this bug with a dynamic import (see commit https://github.com/Eomys/SciDataTool/commit/b0d94289bdc599f0f749314bde3b1fe0aac1c7d8)

I have several bugs to fix, so I will let you know as soon as a new release is ready.

Helene

**Comment by helene-t** [comment]
The new release (1.0.6) is now available with a correction for this issue. Can you confirm if it fixes the issue?

**Comment by SebGue** [comment]
Thank you very much!
