### ISSUE TITLE
[NF] conversion of vibration data (acceleration / velocity / displacement)

### ISSUE THREAD

**Issue by mglesser** [Eomys/SciDataTool#22]
Hello,
When dealing with vibration data it could be nice to be able to convert the data between acceleration, velocity and displacement by using the appropriate "unit" argument. The question of the dB conversion should ideally be adressed (to plot data in dB of velocity from acceleration data for instance).
Thanks

**Comment by helene-t** [comment]
We are going to start working on this issue. The idea would be to use "get_data_along" method to create a new Data object which would be derivated or integrated along a given axis.

This implies developing derivation/integration methods. We also already have an integration method for the time domain (using trapz). For the frequency domain, derivation/integration along time are fairly easy (multiply/divide by 2*j*pi*f). Other methods could be developed later.

Another difficulty will be to obtain the correct unit.

**Comment by helene-t** [comment]
This has been integrated in PR #54
