### ISSUE TITLE
1/3-octave band spectra 

### ISSUE THREAD

**Issue by Sijie-NI** [Eomys/SciDataTool#34]
Hello, I want to plot a 1/3-octave band spectre with Log scale. But it is impossible to fix the width of bars, which always varies with the frequency band. Could we create a new type_plot for adapting to this case?
![Noise_FFT_3rd_oct_Log](https://user-images.githubusercontent.com/64203774/126335729-3e6508e7-0ef4-47ac-9316-6410af76431a.png)

Best regards

**Comment by mglesser** [comment]
I have submitted a PR (#35) that should solve the issue. The nth octave band plots are now better managed with the plot_type='octave' option of plot_2D_Data. 
![image](https://user-images.githubusercontent.com/60893296/126358126-937cdbc1-3030-4615-9b0a-fec87490e7c7.png)

**Comment by Sijie-NI** [comment]
Hello Martin, 

Thank you very much. I am waiting for the validation of your PR. So I will try it as soon as possible. 

Best regards

Sijie
