### ISSUE TITLE
[Bug] get_xyz_along

### ISSUE THREAD

**Issue by Superomeg4** [Eomys/SciDataTool#36]
I have defined a VectorField object, with axes "freqs" (size 1008), "wavenumber" (size48) and "z" .
I wanted to apply get_xyz_along("time=my_value", "angle") and encountered the following bug:
- If my_value is < to the max value of time[smallesperiod], then I get the expected behaviour (a vector of size 48).
- If my_value is > to the max of time[smallesperiod], then I get an uexpected size (8 x 48).

**Comment by helene-t** [comment]
Solved in last release
