### ISSUE TITLE
Numpy dependency

### ISSUE THREAD

**Issue by hakostra** [Eomys/SciDataTool#44]
What is the reason for requiring numpy==1.19.3 exactly? Is this strictly necessary? I want to use [MoSQITo](https://github.com/Eomys/MoSQITo), which depend on SciDataTool. However, since SciDataTool require numpy==1.19.3 this forces a constraint on my entire Python environment. SciDataTool is the only package that has such a strict constraint.

If there is a real, known and identified reason why one cannot use numpy>=1.19.3, that reason should be resolved such that one can be a bit more flexible in which package versions work together...

**Comment by SebGue** [comment]
Hello hakostra,

maybe [this](https://github.com/Eomys/pyleecan/pull/266) will help you in this question.

Best regards, Sebastian

**Comment by SebGue** [comment]
@Superomeg4 have you checked the acutal numpy version if the bug still persists?

**Comment by hakostra** [comment]
Thanks for the hint. I believe this is a note on the issue:
https://github.com/numpy/numpy/wiki/FMod-Bug-on-Windows

I don't have a Windows computer so I cannot check myself, but to me it seems that only 1.19.4 and 1.19.5 are affected by the bug, based on what I can read, and it also seems the bug was really caused by a Windows update that is now resolved:
https://developercommunity.visualstudio.com/t/fmod-after-an-update-to-windows-2004-is-causing-a/1207405

I.e. the bug was not even a numpy bug, but a Windows bug.

Since this has nothing to do with the interaction between SciDataTool and numpy, I would maybe consider to remove the strict version pinning. This is just confusing for users. One might believe that there is for instance an API breakage or something in numpy, which is not the case.

If you insist to still enforce this, I would rather write "numpy>1.19.5,<=1.19.3", or alternatively "numpy>1.19.5".

**Comment by SebGue** [comment]
Thanks for this informations. So I guess you can work around this issue yourself for now?
I can't update SciDataTool on pip (or at least haven't done it yet), so I don't know how long this will take.

**Comment by hakostra** [comment]
I do at least propose some kind of change in the git repo quite soon, even though you do not plan to make a release. Then I can do `pip install git+https://github.com/Eomys/SciDataTool.git` for the moment, which is not too bad.

Alternatives would be to install with `--no-deps` and manage the dependencies separately, i.e.
```
pip install numpy
pip install scipy>=1.4.1 matplotlib>=3.3.2 h5py>=3.2.1 cloudpickle>=1.3.0 pytest>=5.4.1
pip install --no-deps scidatatool
```
A third option is to forke the git repo, make a change and then install it from my forked repo...
But both of these options are quite cumbersome compared to you fixing the requirements.txt...

**Comment by BonneelP** [comment]
Hello,
I have change the content of the requirements.txt. Thank you for noticing :)
Anyway we plan to work on a release in the near future.
Best regards,
Pierre

**Comment by hakostra** [comment]
Thanks. This makes my work easier.
