### ISSUE TITLE
Bug: FFT on data with multiple axes

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#5]
Hello Helene,

it seems, that the FFT is done over all axes of data with multiple axes unintentionally.

Best regards, Sebastian

```
from SciDataTool import Data1D, DataTime
from numpy import linspace, ones_like, cos, pi, tile

time = linspace(0, 1, 8, endpoint=False)
indices = linspace(0, 2, 3, endpoint=True)
field = cos(2 * pi * time) + 0


Time = Data1D(name="time", unit="s", values=time)
Indices = Data1D(name="indices", unit="", values=indices)
y0 = DataTime(name="TestData", axes=[Time], values=field)
y1 = DataTime(name="TestData", axes=[Indices, Time], values=tile(field, (indices.size, 1)))

# y1_fft = y1.time_to_freq()
# y1_ = y1_fft.freq_to_time()

```

**Comment by helene-t** [comment]
Hello Sebastian,

Thank you, this was indeed a bug, that I have just corrected. You can install version 1.1.2 to check that it is now working correctly.

Best regards,
Helene

**Comment by SebGue** [comment]
Hello Helene,

thank you very much. I will check  when I'm back at my office. 
That may save me some time today, since I don't need to think about a workaround. :blush:

BR Sebastian
