### ISSUE TITLE
[NF] new object to store both time and freq data

### ISSUE THREAD

**Issue by helene-t** [Eomys/SciDataTool#52]
In some particular cases, it could be handy to store both time and frequential data, to avoid computing many fft for example. Such an object would contain a DataTime and a DataFreq, and have the same get_along methods which would pick the data in the most appropriate object (DataFreq in case of fft for example). The same logic would be applied to VectorField objects.

Such an object could be named "DataTimeFreq", "DataDual", or "DataBoth". Any other suggestion?

**Comment by SebGue** [comment]
DataTimeFreq 👍

**Comment by mglesser** [comment]
We should keep in mind that sooner or later, we will probably have to define a new Data object to play with short-time fourrier transform. We should be carrefull not to introduce a confusion between your object and this future object (in terms of name in particular).

**Comment by EmileDvs** [comment]
I close this issue since DataDual has been implemented.
