### ISSUE TITLE
[NF] Integral and Differential Calculation

### ISSUE THREAD

**Issue by SebGue** [Eomys/SciDataTool#6]
Hello Helene,

do you have plans to extend SciDataTool with integral and differential calculation abilities?
It may be a great addition to this package.

Best regards, Sebastian

**Comment by jlebesnerais** [comment]
Hello Seb,
What type of integration would like to carry ? you mean for instance to perform space integration (for flux linkage) or time derivation (for back emf) ?
Regards,
Jean

**Comment by SebGue** [comment]
Hello Jean,

yes, such kind of calculations. Fürther it could be interesting have mean, sum, cumsum,... calculations available. Also a function to filter a set of harmonics would be nice.
But I don't know if this exceed the intention of this package.
Best regards, Sebastian

**Comment by jlebesnerais** [comment]
I confirm that all these operations will come very soon, including harmonic filters.

**Comment by helene-t** [comment]
A new feature has just been added for the computation of integrals along an axis. It will be included in the next release.

**Comment by EmileDvs** [comment]
I close this issue since integration, anti-derivation and derivation are available for relevant axes such as x/y/z/time/angle/frequency.
