### ISSUE TITLE
[bug] Normalizations in DataND/plot_3D_Data.

### ISSUE THREAD

**Issue by mglesser** [Eomys/SciDataTool#76]
Normalization syntax haven't been updated in
SciDataTool/SciDataTool/Methods/DataND/plot_3D_Data.py

**Comment by helene-t** [comment]
The syntax has been updated in the Norm_ref or Norm_indices cases. Did you encounter an issue with another Norm object maybe?

**Comment by mglesser** [comment]
The issue was coming from the definition of the data object and will be corrected in a future realease.
